image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -y install git-ftp
          - git ftp push --user $FTP_USER --passwd $FTP_PASSWD ftp://global-patienttransfer.com
